version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
              node -v
              npm -v
      - run:
          name: Install dependencies
          command: |
              sudo npm i -g typescript eslint mocha
              sudo npm i node-fetch@3
              sudo npm i --save-dev typescript-eslint mockttp
      - run:
          name: Prepublish
          command: |
              npm run prepublish
      - run:
          name: Linter
          command: |
              npm run lint
      - run:
          name: Tests
          command: |
              npm run test
