version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
              node -v
              npm -v
      - run:
          name: Install dependencies
          command: |
              sudo npm i --global typescript ts-node node-fetch@3
      - run:
          name: Build distribution
          command: |
              tsc
