version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
              node -v
              npm -v
      - run:
          name: Install dependencies
          command: |
              npm i
      - run:
          name: Prepare
          command: |
              npm run prepare
      - run:
          name: Tests
          command: |
              npm run test
