version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.2.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
              node -v
              npm -v
      - run:
          name: Install packages
          command: |
              npm i typescript js-node node-fetch@3
      - run:
          name: Run tsc
          command: |
              tsc
