version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
              node -v
              npm -v
      - run:
          name: Install dependencies
          command: |
              npm i typescript js-node node-fetch@3
