version: 2
orbs:
  node: circleci/node@22.2   
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
              node -v
              npm -v
      - run:
          name: Install packages
          command: |
              sudo npm i typescript js-node node-fetch@3
      - run:
          name: Run tsc
          command: |
              tsc
