version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install NVM
          command: |
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          name: Install Node
          command: |
              nvm install 22
      - run:
          name: Install packages
          command: |
              npm i typescript js-node node-fetch@3
      - run:
          name: Run tsc
          command: |
              tsc
